
services:
  sql_server:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    container_name: finance_app_sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1234"
    ports: 
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Password@1234" -C -Q "SELECT 1" || exit 1
      interval: 10s
      retries: 10
      start_period: 40s
      timeout: 3s

  webapp:
    build: .
    container_name: finance_app_web
    depends_on:
      sql_server:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      ASPNETCORE_URLS: http://+:8000
      ASPNETCORE_ENVIRONMENT: Production

volumes:
  sql_data:

